language: objective-c
osx_image: xcode7.3
before_install:
 - pod repo update
 - pod install
script:
 - xctool -workspace Eloquence.xcworkspace -scheme Eloquence -sdk macosx10.11 build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
 - xctool -workspace Eloquence.xcworkspace -scheme EloquenceIOS -sdk iphoneos9.3 build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
